default[:serf][:version]          = '0.2.1'
default[:serf][:encrypt_key]      = "XXXXXXXXXXXXXX"
default[:serf][:role]             = "base"
default[:serf][:encrypt_rpc_port] = 7374
default[:serf][:rpc_addr]         = node[:ipaddress] + ":#{node.default[:serf][:encrypt_rpc_port]}"
default[:serf][:start_join]       = []
default[:serf][:event_handlers]   = []
default[:serf][:url]              = "https://dl.bintray.com/mitchellh/serf/#{node[:serf][:version]}_linux_amd64.zip"
default[:serf][:path]             = '/usr/local/bin'
